### ISSUE TITLE
SQL Generator doesn't raise issues if the user demands too many columns

### ISSUE THREAD

**Issue by saltzm** [saltzm/yadi#12]
Query transformed into: movie(A):-movie(A,B,C,D,E,F)
2013-11-20 14:02:06,699 INFO sqlalchemy.engine.base.Engine SELECT movie._0 as A FROM movie;
2013-11-20 14:02:06,699 INFO sqlalchemy.engine.base.Engine {}
+------------------------+
| Home Alone             |
+------------------------+
| Life Is Beautiful      |
+------------------------+
| Casino                 |
+------------------------+
| Toy Story              |
+------------------------+
| No Country for Old Men |
+------------------------+
yadi> movie(E) :- movie(A, B, C, D, E, F).
Original query before processing: movie(E):-movie(A,B,C,D,E,F)
Info:
Query transformed into: movie(E):-movie(A,B,C,D,E,F)
2013-11-20 14:02:12,415 INFO sqlalchemy.engine.base.Engine SELECT movie._4 as E FROM movie;
2013-11-20 14:02:12,415 INFO sqlalchemy.engine.base.Engine {}
2013-11-20 14:02:12,419 INFO sqlalchemy.engine.base.Engine ROLLBACK
(ProgrammingError) column movie._4 does not exist
LINE 1: SELECT movie._4 as E FROM movie;
               ^
 'SELECT movie._4 as E FROM movie;' {}

Since the SQL selects only based on head variables, if you do something like movie(A):-movie(A,B,C,D,E,F), even if there are only 3 columns in the movie relation, it will return successfully instead of raising an error. I think it should raise an error.

**Comment by frandres** [comment]
this has not been fixed, but we are closing on the grounds that its not a priority
