### ISSUE TITLE
Variables of length > 1 not being recognized

### ISSUE THREAD

**Issue by frandres** [saltzm/yadi#23]
r(M,A):- movie(M, 'Ethan Coen', _,_), featuring (M,A,_,_). is functioning

r(M,Ac):- movie(M,'Ethan Coen', _,_), featuring (M,Ac,_,_). is not functioning

The only difference is the name of the actor variable A, Ac. Shouldn't Ac be accepted?

**Comment by saltzm** [comment]
Turns out length isn't the problem, it's the isVariable method in @caioseguin code in the RuleHandler class. Fixing now.
